// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma 7: the CLI reads the datasource URL from here (dotenv loads .env).
// The runtime client receives the same URL via `datasourceUrl` (see src/lib/db.ts).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use the direct (session) connection; the runtime client uses
    // the transaction pooler via the driver adapter (see src/lib/db.ts).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
